accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='accounts'
urlpatterns = [
    path('', views.signin, name="signin"),
    path('signup/', views.signup, name="signup"),
    path('logout/',views.logout_view,name="logout"),
    
]

automl/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name='automl'
urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('upload/',views.upload_file, name="upload"),
    path('chart/',views.chart, name="chart"),
    path('table/',views.table, name="table"),
    path('howdoi/',views.howdoi_view, name="howdoi"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xai/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('test/',views.main),
    path('automl/',include('automl.urls')),
]

xai/views.py
from django.shortcuts import render
from django.http import HttpResponse


from module.monitor import get_statistics
# Create your views here.
def main(request):
    statistics=get_statistics()
    print(statistics)
    return render(request, 'dashboard.html')

xai/templates/aside.html
{% load static %}
<!--sidebar start-->
<aside>
    <div id="sidebar" class="nav-collapse ">
      <!-- sidebar menu start-->
      <ul class="sidebar-menu" id="nav-accordion">
        <p class="centered"><a href="{% url 'automl:dashboard' %}"><img src="{% static 'img/ui-sam.jpg' %}" class="img-circle" width="80"></a></p>
        <h5 class="centered">{{user.nickname}}</h5>
        <li class="mt">
          <a href="{% url 'automl:dashboard' %}">
            <i class="fa fa-dashboard"></i>
            <span>Dashboard</span>
            </a>
        </li>
        <li class="sub-menu">
          <a href="javascript:;">
            <i class="fa fa-cogs"></i>
            <span>Components</span>
            </a>
          <ul class="sub">
            <li><a href="{% url 'automl:upload'%}">Fild upload</a></li>
          </ul>
        </li>
        <li class="sub-menu">
          <a href="{% url 'automl:chart' %}">
            
            <i class=" fa fa-bar-chart-o"></i>
            <span>Charts</span>
            </a>
        </li>
        <li class="sub-menu">
          <a href="{% url 'automl:table' %}">
            <i class="fa fa-th"></i>
            <span>Data Tables</span>
            </a>
        </li>
        <li class="sub-menu">
          <a href="javascript:;">
            <i class="fa fa-desktop"></i>
            <span>Reports</span>
            </a>
          <ul class="sub">
            <li><a href="morris.html">Morris</a></li>
            <li><a href="chartjs.html">Chartjs</a></li>
            <li><a href="flot_chart.html">Flot Charts</a></li>
            <li><a href="xchart.html">xChart</a></li>
          </ul>
        </li>
        <li class="sub-menu">
          <a href="{% url 'automl:howdoi' %}">
            <i class="fa fa-comments-o"></i>
            <span>XAI-QnA</span>
            </a>
        </li>
      </ul>
      <!-- sidebar menu end-->
    </div>
  </aside>
  <!--sidebar end-->

xai/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>Penta - XAI</title>

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--external css-->
  <link href="{% static 'lib/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/zabuto_calendar.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'lib/gritter/css/jquery.gritter.css' %}" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
  <script src="{% static 'lib/chart-master/Chart.js' %}"></script>

  <!-- =======================================================
    Template Name: Dashio
    Template URL: https://templatemag.com/dashio-bootstrap-admin-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>
  <section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
        {% include 'header.html' %}
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
        {% include 'aside.html' %}
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        {% block content %}
        {% endblock %}
        <!-- /row -->
      </section>
    </section>
    <!--main content end-->
    {% include 'footer.html' %}
  </section>
    {% include 'script.html' %}
</body>

</html>

xai/templates/chart_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>Dashio - Bootstrap Admin Template</title>

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--external css-->
  <link href="{% static 'lib/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
  <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
  
  <link rel="stylesheet" href="{% static 'lib/xchart/xcharts.css' %}">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">

  <!-- =======================================================
    Template Name: Dashio
    Template URL: https://templatemag.com/dashio-bootstrap-admin-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>
  <section id="container">
    <!-- **********************************************************************************************************************************************************
        TOP BAR CONTENT & NOTIFICATIONS
        *********************************************************************************************************************************************************** -->
    {% include 'header.html' %}
    <!-- **********************************************************************************************************************************************************
        MAIN SIDEBAR MENU
        *********************************************************************************************************************************************************** -->
    {% include 'aside.html' %}
    <!-- **********************************************************************************************************************************************************
        MAIN CONTENT
        *********************************************************************************************************************************************************** -->
    {% block content %}
    {% endblock %}
    <!--main content end-->
    <!--footer start-->
    <footer class="site-footer">
      <div class="text-center">
        <p>
          &copy; Copyrights <strong>Dashio</strong>. All Rights Reserved
        </p>
        <div class="credits">
          <!--
            You are NOT allowed to delete the credit link to TemplateMag with free version.
            You can delete the credit link only if you bought the pro version.
            Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/dashio-bootstrap-admin-template/
            Licensing information: https://templatemag.com/license/
          -->
          Created with Dashio template by <a href="https://templatemag.com/">TemplateMag</a>
        </div>
        <a href="chartjs.html#" class="go-top">
          <i class="fa fa-angle-up"></i>
          </a>
      </div>
    </footer>
    <!--footer end-->
  </section>
  <!-- js placed at the end of the document so the pages load faster -->
  
  
  
  
  
 
  
    <!--script for this page-->
    <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
    <script class="include" type="text/javascript" src="{% static 'lib/jquery.dcjqaccordion.2.7.js' %}"></script>
    <script src="{% static 'lib/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'lib/jquery.nicescroll.js' %}" type="text/javascript"></script>
    
    <script src="{% static 'lib/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'lib/morris/morris.min.js' %}"></script>
    
    <!--common script for all pages-->
    <script src="{% static 'lib/common-scripts.js' %}"></script>
    <!--script for this page-->
    <script src="{% static 'lib/morris-conf.js' %}"></script>

    <!--script for this page-->
    <script src="{% static 'lib/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'lib/flot/jquery.flot.resize.js' %}"></script>
    <script src="{% static 'lib/flot/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'lib/flot/jquery.flot.crosshair.js' %}"></script>
    <script src="{% static 'lib/flotchart-conf.js' %}"></script>
    <!--script for this page-->
    <script src="{% static 'lib/xchart/d3.v3.min.js' %}"></script>
    <script src="{% static 'lib/xchart/xcharts.min.js' %}"></script>
    <!--script for this page-->
    <script src="{% static 'lib/chart-master/Chart.js' %}"></script>
    <script src="{% static 'lib/chartjs-conf.js' %}"></script>
 
<script>
(function() {
    var data = [{
    "xScale": "ordinal",
    "comp": [],
    "main": [{
        "className": ".main.l1",
        "data": [{
        "y": 15,
        "x": "2012-11-19T00:00:00"
        }, {
        "y": 11,
        "x": "2012-11-20T00:00:00"
        }, {
        "y": 8,
        "x": "2012-11-21T00:00:00"
        }, {
        "y": 10,
        "x": "2012-11-22T00:00:00"
        }, {
        "y": 1,
        "x": "2012-11-23T00:00:00"
        }, {
        "y": 6,
        "x": "2012-11-24T00:00:00"
        }, {
        "y": 8,
        "x": "2012-11-25T00:00:00"
        }]
    }, {
        "className": ".main.l2",
        "data": [{
        "y": 29,
        "x": "2012-11-19T00:00:00"
        }, {
        "y": 33,
        "x": "2012-11-20T00:00:00"
        }, {
        "y": 13,
        "x": "2012-11-21T00:00:00"
        }, {
        "y": 16,
        "x": "2012-11-22T00:00:00"
        }, {
        "y": 7,
        "x": "2012-11-23T00:00:00"
        }, {
        "y": 18,
        "x": "2012-11-24T00:00:00"
        }, {
        "y": 8,
        "x": "2012-11-25T00:00:00"
        }]
    }],
    "type": "line-dotted",
    "yScale": "linear"
    }, {
    "xScale": "ordinal",
    "comp": [],
    "main": [{
        "className": ".main.l1",
        "data": [{
        "y": 12,
        "x": "2012-11-19T00:00:00"
        }, {
        "y": 18,
        "x": "2012-11-20T00:00:00"
        }, {
        "y": 8,
        "x": "2012-11-21T00:00:00"
        }, {
        "y": 7,
        "x": "2012-11-22T00:00:00"
        }, {
        "y": 6,
        "x": "2012-11-23T00:00:00"
        }, {
        "y": 12,
        "x": "2012-11-24T00:00:00"
        }, {
        "y": 8,
        "x": "2012-11-25T00:00:00"
        }]
    }, {
        "className": ".main.l2",
        "data": [{
        "y": 29,
        "x": "2012-11-19T00:00:00"
        }, {
        "y": 33,
        "x": "2012-11-20T00:00:00"
        }, {
        "y": 13,
        "x": "2012-11-21T00:00:00"
        }, {
        "y": 16,
        "x": "2012-11-22T00:00:00"
        }, {
        "y": 7,
        "x": "2012-11-23T00:00:00"
        }, {
        "y": 18,
        "x": "2012-11-24T00:00:00"
        }, {
        "y": 8,
        "x": "2012-11-25T00:00:00"
        }]
    }],
    "type": "cumulative",
    "yScale": "linear"
    }, {
    "xScale": "ordinal",
    "comp": [],
    "main": [{
        "className": ".main.l1",
        "data": [{
        "y": 12,
        "x": "2012-11-19T00:00:00"
        }, {
        "y": 18,
        "x": "2012-11-20T00:00:00"
        }, {
        "y": 8,
        "x": "2012-11-21T00:00:00"
        }, {
        "y": 7,
        "x": "2012-11-22T00:00:00"
        }, {
        "y": 6,
        "x": "2012-11-23T00:00:00"
        }, {
        "y": 12,
        "x": "2012-11-24T00:00:00"
        }, {
        "y": 8,
        "x": "2012-11-25T00:00:00"
        }]
    }, {
        "className": ".main.l2",
        "data": [{
        "y": 29,
        "x": "2012-11-19T00:00:00"
        }, {
        "y": 33,
        "x": "2012-11-20T00:00:00"
        }, {
        "y": 13,
        "x": "2012-11-21T00:00:00"
        }, {
        "y": 16,
        "x": "2012-11-22T00:00:00"
        }, {
        "y": 7,
        "x": "2012-11-23T00:00:00"
        }, {
        "y": 18,
        "x": "2012-11-24T00:00:00"
        }, {
        "y": 8,
        "x": "2012-11-25T00:00:00"
        }]
    }],
    "type": "bar",
    "yScale": "linear"
    }];
    var order = [0, 1, 0, 2],
    i = 0,
    xFormat = d3.time.format('%A'),
    chart = new xChart('line-dotted', data[order[i]], '#chart', {
        axisPaddingTop: 5,
        dataFormatX: function(x) {
        return new Date(x);
        },
        tickFormatX: function(x) {
        return xFormat(x);
        },
        timing: 1250
    }),
    rotateTimer,
    toggles = d3.selectAll('.multi button'),
    t = 3500;

    function updateChart(i) {
    var d = data[i];
    chart.setData(d);
    toggles.classed('toggled', function() {
        return (d3.select(this).attr('data-type') === d.type);
    });
    return d;
    }

    toggles.on('click', function(d, i) {
    clearTimeout(rotateTimer);
    updateChart(i);
    });

    function rotateChart() {
    i += 1;
    i = (i >= order.length) ? 0 : i;
    var d = updateChart(order[i]);
    rotateTimer = setTimeout(rotateChart, t);
    }
    rotateTimer = setTimeout(rotateChart, t);
}());
</script>

</body>

</html>

xai/templates/footer.html
<!--footer start-->
<footer class="site-footer">
    <div class="text-center">
      <p>
        &copy; Copyrights <strong>PENTA-XAI</strong>. All Rights Reserved
      </p>
      <div class="credits">
        <!--
          You are NOT allowed to delete the credit link to TemplateMag with free version.
          You can delete the credit link only if you bought the pro version.
          Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/dashio-bootstrap-admin-template/
          Licensing information: https://templatemag.com/license/
        -->
        Created with PentaSystem template by <a href="http://www.penta.co.kr/">PentaSystem</a>
      </div>
      <a href="index.html#" class="go-top">
        <i class="fa fa-angle-up"></i>
        </a>
    </div>
  </footer>
  <!--footer end-->

xai/templates/header.html
{% load static %}
<!--header start-->
    <header class="header black-bg">
        <div class="sidebar-toggle-box">
          <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
        <!--logo start-->
        <a href="{% url 'automl:dashboard' %}" class="logo"><b>PENTA<span>-XAI</span></b></a>
        <!--logo end-->
        <div class="nav notify-row" id="top_menu">
          <!--  notification start -->
          <ul class="nav top-menu">
            <!-- settings start -->
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                <i class="fa fa-tasks"></i>
                <span class="badge bg-theme">4</span>
                </a>
              <ul class="dropdown-menu extended tasks-bar">
                <div class="notify-arrow notify-arrow-green"></div>
                <li>
                  <p class="green">You have 4 pending tasks</p>
                </li>
                <li>
                  <a href="index.html#">
                    <div class="task-info">
                      <div class="desc">Dashio Admin Panel</div>
                      <div class="percent">40%</div>
                    </div>
                    <div class="progress progress-striped">
                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                        <span class="sr-only">40% Complete (success)</span>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="index.html#">
                    <div class="task-info">
                      <div class="desc">Database Update</div>
                      <div class="percent">60%</div>
                    </div>
                    <div class="progress progress-striped">
                      <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                        <span class="sr-only">60% Complete (warning)</span>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="index.html#">
                    <div class="task-info">
                      <div class="desc">Product Development</div>
                      <div class="percent">80%</div>
                    </div>
                    <div class="progress progress-striped">
                      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="index.html#">
                    <div class="task-info">
                      <div class="desc">Payments Sent</div>
                      <div class="percent">70%</div>
                    </div>
                    <div class="progress progress-striped">
                      <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%">
                        <span class="sr-only">70% Complete (Important)</span>
                      </div>
                    </div>
                  </a>
                </li>
                <li class="external">
                  <a href="#">See All Tasks</a>
                </li>
              </ul>
            </li>
            <!-- settings end -->
            <!-- inbox dropdown start-->
            <li id="header_inbox_bar" class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                <i class="fa fa-envelope-o"></i>
                <span class="badge bg-theme">5</span>
                </a>
              <ul class="dropdown-menu extended inbox">
                <div class="notify-arrow notify-arrow-green"></div>
                <li>
                  <p class="green">You have 5 new messages</p>
                </li>
                <li>
                  <a href="index.html#">
                    <span class="photo"><img alt="avatar" src="{% static 'img/ui-zac.jpg' %}"></span>
                    <span class="subject">
                    <span class="from">Zac Snider</span>
                    <span class="time">Just now</span>
                    </span>
                    <span class="message">
                    Hi mate, how is everything?
                    </span>
                    </a>
                </li>
                <li>
                  <a href="index.html#">
                    <span class="photo"><img alt="avatar" src="{% static 'img/ui-divya.jpg' %}"></span>
                    <span class="subject">
                    <span class="from">Divya Manian</span>
                    <span class="time">40 mins.</span>
                    </span>
                    <span class="message">
                    Hi, I need your help with this.
                    </span>
                    </a>
                </li>
                <li>
                  <a href="index.html#">
                    <span class="photo"><img alt="avatar" src="{% static 'img/ui-danro.jpg' %}"></span>
                    <span class="subject">
                    <span class="from">Dan Rogers</span>
                    <span class="time">2 hrs.</span>
                    </span>
                    <span class="message">
                    Love your new Dashboard.
                    </span>
                    </a>
                </li>
                <li>
                  <a href="index.html#">
                    <span class="photo"><img alt="avatar" src="{% static 'img/ui-sherman.jpg' %}"></span>
                    <span class="subject">
                    <span class="from">Dj Sherman</span>
                    <span class="time">4 hrs.</span>
                    </span>
                    <span class="message">
                    Please, answer asap.
                    </span>
                    </a>
                </li>
                <li>
                  <a href="index.html#">See all messages</a>
                </li>
              </ul>
            </li>
            <!-- inbox dropdown end -->
            <!-- notification dropdown start-->
            <li id="header_notification_bar" class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="index.html#">
                <i class="fa fa-bell-o"></i>
                <span class="badge bg-warning">7</span>
                </a>
              <ul class="dropdown-menu extended notification">
                <div class="notify-arrow notify-arrow-yellow"></div>
                <li>
                  <p class="yellow">You have 7 new notifications</p>
                </li>
                <li>
                  <a href="index.html#">
                    <span class="label label-danger"><i class="fa fa-bolt"></i></span>
                    Server Overloaded.
                    <span class="small italic">4 mins.</span>
                    </a>
                </li>
                <li>
                  <a href="index.html#">
                    <span class="label label-warning"><i class="fa fa-bell"></i></span>
                    Memory #2 Not Responding.
                    <span class="small italic">30 mins.</span>
                    </a>
                </li>
                <li>
                  <a href="index.html#">
                    <span class="label label-danger"><i class="fa fa-bolt"></i></span>
                    Disk Space Reached 85%.
                    <span class="small italic">2 hrs.</span>
                    </a>
                </li>
                <li>
                  <a href="index.html#">
                    <span class="label label-success"><i class="fa fa-plus"></i></span>
                    New User Registered.
                    <span class="small italic">3 hrs.</span>
                    </a>
                </li>
                <li>
                  <a href="index.html#">See all notifications</a>
                </li>
              </ul>
            </li>
            <!-- notification dropdown end -->
          </ul>
          <!--  notification end -->
        </div>
        <div class="top-menu">
          <ul class="nav pull-right top-menu">
            <li><a class="logout" href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        </div>
      </header>
      <!--header end-->

xai/templates/login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="Dashboard">
  <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
  <title>Dashio - Bootstrap Admin Template</title>

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!--external css-->
  <link href="{% static 'lib/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
  
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">
  
  <!-- =======================================================
    Template Name: Dashio
    Template URL: https://templatemag.com/dashio-bootstrap-admin-template/
    Author: TemplateMag.com
    License: https://templatemag.com/license/
  ======================================================= -->
</head>

<body>
  <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
  <div id="login-page">
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <!-- js placed at the end of the document so the pages load faster -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
  <!--BACKSTRETCH-->
  <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
  <script type="text/javascript" src="{% static 'lib/jquery.backstretch.min.js' %}"></script>
  <script>
    $.backstretch("{% static 'img/login-bg.jpg' %}", {
      speed: 500
    });
  </script>
</body>

</html>

xai/templates/script.html
{% load static %}
<!-- js placed at the end of the document so the pages load faster -->
<script src="{% static 'lib/jquery/jquery.min.js' %}"></script>

<script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
<script class="include" type="text/javascript" src="{% static 'lib/jquery.dcjqaccordion.2.7.js' %}"></script>
<script src="{% static 'lib/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'lib/jquery.nicescroll.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/jquery.sparkline.js' %}"></script>
<!--common script for all pages-->
<script src="{% static 'lib/common-scripts.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/gritter/js/jquery.gritter.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/gritter-conf.js' %}"></script>
<!--script for this page-->
<script src="{% static 'lib/sparkline-chart.js' %}"></script>
<script src="{% static 'lib/zabuto_calendar.js' %}"></script>
<script type="application/javascript">
  $(document).ready(function() {
    $("#date-popover").popover({
      html: true,
      trigger: "manual"
    });
    $("#date-popover").hide();
    $("#date-popover").click(function(e) {
      $(this).hide();
    });

    $("#my-calendar").zabuto_calendar({
      action: function() {
        return myDateFunction(this.id, false);
      },
      action_nav: function() {
        return myNavFunction(this.id);
      },
      ajax: {
        url: "show_data.php?action=1",
        modal: true
      },
      legend: [{
          type: "text",
          label: "Special event",
          badge: "00"
        },
        {
          type: "block",
          label: "Regular event",
        }
      ]
    });
  });

  function myNavFunction(id) {
    $("#date-popover").hide();
    var nav = $("#" + id).data("navigation");
    var to = $("#" + id).data("to");
    console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
  }
</script>